# Generated by Django 5.2.8 on 2025-12-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogoyda_weather_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryOfSearch',
        ),
    ]
